version: '3'

services:
  database:
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=todo_app_db
