name: Test
on:
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
# https://turbo.build/repo/docs/ci/github-actions
# https://pnpm.io/continuous-integration#github-actions
# https://docs.docker.com/engine/reference/commandline/create/#options
#TODO: only run format, lint and tests where necessary. Add vitest coverage
jobs:
  test:
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres_user
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_DB: todo_app_db
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
          --tmpfs /var/lib/postgresql/data
        ports:
          - 5432:5432
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: install atlas
        uses: ariga/setup-atlas@v0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check types
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Format
        run: pnpm run format

      - name: Push schema to test db
        run: pnpm run db:schema-push

      - name: Running tests
        run: pnpm run test
