name: Test
on:
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
jobs:
  test:
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres_user
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_DB: todo_app_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: install atlas
        uses: ariga/setup-atlas@v0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check types
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Format
        run: pnpm run format

      - name: Push schema to test db
        run: pnpm run db:schema-push

      - name: Running tests
        run: pnpm run test
